name: GitHub Actions Demo

Â 

on:

Â  push:

Â Â Â  branches: [ main ]

Â Â Â  paths-ignore: [.github/**]

Â  pull_request:

Â Â Â  branches: [ main ]

Â  schedule:

Â Â Â  - cron: '15 6 * * 0'

Â  workflow_dispatch:

Â Â 

jobs:

Â  Build:

Â Â Â  runs-on: ubuntu-latest

Â Â Â  steps:

Â Â Â Â Â  - run: |

Â Â Â Â Â Â Â Â Â  echo "ðŸŽ‰ The job was triggered by event: ${{ github.event_name }}"

Â Â Â Â Â Â Â Â Â  echo "ðŸ”Ž The name of your branch is ${{ github.ref }} and your repository is ."

Â 

Â Â Â Â Â  - uses: actions/checkout@v3.3.0

Â 

Â Â Â Â Â  - name: List files in the repository

Â Â Â Â Â Â Â  run: |

Â Â Â Â Â Â Â Â Â  echo "The repository ${{ github.repository }} contains the following files:"

Â Â Â Â Â Â Â Â Â  tree
